spring.datasource.url=jdbc:postgresql://localhost:5432/bookapi
spring.datasource.username=postgres
spring.datasource.password=${SECRET_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${SECRET_JWTSECRET}
jwt.expiration=${SECRET_JWTEXPIRATIONINMS}

spring.config.import=optional:classpath:application-secret.properties

logging.level.com.bookreview.api=DEBUG
#logging.file.name=logs/api.log